spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermarket_management?useSSL=false&serverTimezone=UTC
    username: root
    password: 19072005
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  jackson:
    serialization:
      INDENT_OUTPUT: true


server:
  port: 8080


logging:
  level:
    org.springframework: INFO
    com.supermarket.management: DEBUG